### PR TITLE
Support version of preference fragment

### PR DESCRIPTION
**Pull request by Tunous**
This pull requests adds support version of the preference fragment for use in projects which depend on them.

### CODE REVIEW

**Comment by roundhill** [comment]
@daniloercoli any thoughts on this? We wouldn't need to update WordPress as long as it used the current version.

This allows Simplenote to use the support preference fragment to get switches and whatnot looking better on pre-lollipop devices.

**Comment by daniloercoli** [comment]
I think we can merge this!

**Comment by roundhill** [comment]
Merged! @daniloercoli can you publish a new release to maven?

**Comment by daniloercoli** [comment]
@roundhill Sure, tracking it here: https://github.com/wordpress-mobile/PasscodeLock-Android/pull/41

**Pull request merged**
